// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/tasks/tasks.proto

package taskspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskStatus int32

const (
	TaskStatus_TASK_STATUS_TODO        TaskStatus = 0
	TaskStatus_TASK_STATUS_IN_PROGRESS TaskStatus = 1
	TaskStatus_TASK_STATUS_DONE        TaskStatus = 2
	TaskStatus_TASK_STATUS_ARCHIVED    TaskStatus = 3
)

// Enum value maps for TaskStatus.
var (
	TaskStatus_name = map[int32]string{
		0: "TASK_STATUS_TODO",
		1: "TASK_STATUS_IN_PROGRESS",
		2: "TASK_STATUS_DONE",
		3: "TASK_STATUS_ARCHIVED",
	}
	TaskStatus_value = map[string]int32{
		"TASK_STATUS_TODO":        0,
		"TASK_STATUS_IN_PROGRESS": 1,
		"TASK_STATUS_DONE":        2,
		"TASK_STATUS_ARCHIVED":    3,
	}
)

func (x TaskStatus) Enum() *TaskStatus {
	p := new(TaskStatus)
	*p = x
	return p
}

func (x TaskStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_tasks_tasks_proto_enumTypes[0].Descriptor()
}

func (TaskStatus) Type() protoreflect.EnumType {
	return &file_proto_tasks_tasks_proto_enumTypes[0]
}

func (x TaskStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskStatus.Descriptor instead.
func (TaskStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 0 => без категории
	CategoryId    int64                  `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        TaskStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=tasks.v1.TaskStatus" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Task) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *Task) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetStatus() TaskStatus {
	if x != nil {
		return x.Status
	}
	return TaskStatus_TASK_STATUS_TODO
}

func (x *Task) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Task) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type CreateTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 0 => без категории
	CategoryId    int64  `protobuf:"varint,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Если oneof не выбран не фильтруем по статусу
	//
	// Types that are valid to be assigned to StatusFilter:
	//
	//	*ListTaskRequest_Status
	StatusFilter isListTaskRequest_StatusFilter `protobuf_oneof:"status_filter"`
	// Types that are valid to be assigned to CategoryFilter:
	//
	//	*ListTaskRequest_CategoryId
	//	*ListTaskRequest_WithoutCategory
	CategoryFilter isListTaskRequest_CategoryFilter `protobuf_oneof:"category_filter"`
	Limit          int32                            `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset         int32                            `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTaskRequest) Reset() {
	*x = ListTaskRequest{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskRequest) ProtoMessage() {}

func (x *ListTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskRequest.ProtoReflect.Descriptor instead.
func (*ListTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{3}
}

func (x *ListTaskRequest) GetStatusFilter() isListTaskRequest_StatusFilter {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

func (x *ListTaskRequest) GetStatus() TaskStatus {
	if x != nil {
		if x, ok := x.StatusFilter.(*ListTaskRequest_Status); ok {
			return x.Status
		}
	}
	return TaskStatus_TASK_STATUS_TODO
}

func (x *ListTaskRequest) GetCategoryFilter() isListTaskRequest_CategoryFilter {
	if x != nil {
		return x.CategoryFilter
	}
	return nil
}

func (x *ListTaskRequest) GetCategoryId() int64 {
	if x != nil {
		if x, ok := x.CategoryFilter.(*ListTaskRequest_CategoryId); ok {
			return x.CategoryId
		}
	}
	return 0
}

func (x *ListTaskRequest) GetWithoutCategory() bool {
	if x != nil {
		if x, ok := x.CategoryFilter.(*ListTaskRequest_WithoutCategory); ok {
			return x.WithoutCategory
		}
	}
	return false
}

func (x *ListTaskRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTaskRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type isListTaskRequest_StatusFilter interface {
	isListTaskRequest_StatusFilter()
}

type ListTaskRequest_Status struct {
	Status TaskStatus `protobuf:"varint,1,opt,name=status,proto3,enum=tasks.v1.TaskStatus,oneof"`
}

func (*ListTaskRequest_Status) isListTaskRequest_StatusFilter() {}

type isListTaskRequest_CategoryFilter interface {
	isListTaskRequest_CategoryFilter()
}

type ListTaskRequest_CategoryId struct {
	CategoryId int64 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof"` // задачи в конкретной категории
}

type ListTaskRequest_WithoutCategory struct {
	WithoutCategory bool `protobuf:"varint,3,opt,name=without_category,json=withoutCategory,proto3,oneof"` // только задачи без категории
}

func (*ListTaskRequest_CategoryId) isListTaskRequest_CategoryFilter() {}

func (*ListTaskRequest_WithoutCategory) isListTaskRequest_CategoryFilter() {}

type ListTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskResponse) Reset() {
	*x = ListTaskResponse{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskResponse) ProtoMessage() {}

func (x *ListTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskResponse.ProtoReflect.Descriptor instead.
func (*ListTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{4}
}

func (x *ListTaskResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type UpdateTaskRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// 0 => снять категорию
	CategoryId    *int64                 `protobuf:"varint,2,opt,name=category_id,json=categoryId,proto3,oneof" json:"category_id,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,4,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Status        *TaskStatus            `protobuf:"varint,5,opt,name=status,proto3,enum=tasks.v1.TaskStatus,oneof" json:"status,omitempty"`
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,6,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTaskRequest) Reset() {
	*x = UpdateTaskRequest{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTaskRequest) ProtoMessage() {}

func (x *UpdateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTaskRequest.ProtoReflect.Descriptor instead.
func (*UpdateTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateTaskRequest) GetCategoryId() int64 {
	if x != nil && x.CategoryId != nil {
		return *x.CategoryId
	}
	return 0
}

func (x *UpdateTaskRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateTaskRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateTaskRequest) GetStatus() TaskStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return TaskStatus_TASK_STATUS_TODO
}

func (x *UpdateTaskRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_proto_tasks_tasks_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tasks_tasks_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_tasks_tasks_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteTaskRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_proto_tasks_tasks_proto protoreflect.FileDescriptor

const file_proto_tasks_tasks_proto_rawDesc = "" +
	"\n" +
	"\x17proto/tasks/tasks.proto\x12\btasks.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\"\x91\x02\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vcategory_id\x18\x02 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12,\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.tasks.v1.TaskStatusR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"j\n" +
	"\x11CreateTaskRequest\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\" \n" +
	"\x0eGetTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xe3\x01\n" +
	"\x0fListTaskRequest\x12.\n" +
	"\x06status\x18\x01 \x01(\x0e2\x14.tasks.v1.TaskStatusH\x00R\x06status\x12!\n" +
	"\vcategory_id\x18\x02 \x01(\x03H\x01R\n" +
	"categoryId\x12+\n" +
	"\x10without_category\x18\x03 \x01(\bH\x01R\x0fwithoutCategory\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offsetB\x0f\n" +
	"\rstatus_filterB\x11\n" +
	"\x0fcategory_filter\"8\n" +
	"\x10ListTaskResponse\x12$\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0e.tasks.v1.TaskR\x05tasks\"\xad\x02\n" +
	"\x11UpdateTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12$\n" +
	"\vcategory_id\x18\x02 \x01(\x03H\x00R\n" +
	"categoryId\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x04 \x01(\tH\x02R\vdescription\x88\x01\x01\x121\n" +
	"\x06status\x18\x05 \x01(\x0e2\x14.tasks.v1.TaskStatusH\x03R\x06status\x88\x01\x01\x12;\n" +
	"\vupdate_mask\x18\x06 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMaskB\x0e\n" +
	"\f_category_idB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\t\n" +
	"\a_status\"#\n" +
	"\x11DeleteTaskRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id*o\n" +
	"\n" +
	"TaskStatus\x12\x14\n" +
	"\x10TASK_STATUS_TODO\x10\x00\x12\x1b\n" +
	"\x17TASK_STATUS_IN_PROGRESS\x10\x01\x12\x14\n" +
	"\x10TASK_STATUS_DONE\x10\x02\x12\x18\n" +
	"\x14TASK_STATUS_ARCHIVED\x10\x032\xf9\x02\n" +
	"\fTasksService\x129\n" +
	"\n" +
	"CreateTask\x12\x1b.tasks.v1.CreateTaskRequest\x1a\x0e.tasks.v1.Task\x123\n" +
	"\aGetTask\x12\x18.tasks.v1.GetTaskRequest\x1a\x0e.tasks.v1.Task\x12A\n" +
	"\bListTask\x12\x19.tasks.v1.ListTaskRequest\x1a\x1a.tasks.v1.ListTaskResponse\x129\n" +
	"\n" +
	"UpdateTask\x12\x1b.tasks.v1.UpdateTaskRequest\x1a\x0e.tasks.v1.Task\x12A\n" +
	"\n" +
	"DeleteTask\x12\x1b.tasks.v1.DeleteTaskRequest\x1a\x16.google.protobuf.Empty\x128\n" +
	"\x04Ping\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B8Z6task-manager-microservice/services/proto/tasks;taskspbb\x06proto3"

var (
	file_proto_tasks_tasks_proto_rawDescOnce sync.Once
	file_proto_tasks_tasks_proto_rawDescData []byte
)

func file_proto_tasks_tasks_proto_rawDescGZIP() []byte {
	file_proto_tasks_tasks_proto_rawDescOnce.Do(func() {
		file_proto_tasks_tasks_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tasks_tasks_proto_rawDesc), len(file_proto_tasks_tasks_proto_rawDesc)))
	})
	return file_proto_tasks_tasks_proto_rawDescData
}

var file_proto_tasks_tasks_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_tasks_tasks_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_tasks_tasks_proto_goTypes = []any{
	(TaskStatus)(0),               // 0: tasks.v1.TaskStatus
	(*Task)(nil),                  // 1: tasks.v1.Task
	(*CreateTaskRequest)(nil),     // 2: tasks.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),        // 3: tasks.v1.GetTaskRequest
	(*ListTaskRequest)(nil),       // 4: tasks.v1.ListTaskRequest
	(*ListTaskResponse)(nil),      // 5: tasks.v1.ListTaskResponse
	(*UpdateTaskRequest)(nil),     // 6: tasks.v1.UpdateTaskRequest
	(*DeleteTaskRequest)(nil),     // 7: tasks.v1.DeleteTaskRequest
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil), // 9: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_proto_tasks_tasks_proto_depIdxs = []int32{
	0,  // 0: tasks.v1.Task.status:type_name -> tasks.v1.TaskStatus
	8,  // 1: tasks.v1.Task.created_at:type_name -> google.protobuf.Timestamp
	8,  // 2: tasks.v1.Task.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 3: tasks.v1.ListTaskRequest.status:type_name -> tasks.v1.TaskStatus
	1,  // 4: tasks.v1.ListTaskResponse.tasks:type_name -> tasks.v1.Task
	0,  // 5: tasks.v1.UpdateTaskRequest.status:type_name -> tasks.v1.TaskStatus
	9,  // 6: tasks.v1.UpdateTaskRequest.update_mask:type_name -> google.protobuf.FieldMask
	2,  // 7: tasks.v1.TasksService.CreateTask:input_type -> tasks.v1.CreateTaskRequest
	3,  // 8: tasks.v1.TasksService.GetTask:input_type -> tasks.v1.GetTaskRequest
	4,  // 9: tasks.v1.TasksService.ListTask:input_type -> tasks.v1.ListTaskRequest
	6,  // 10: tasks.v1.TasksService.UpdateTask:input_type -> tasks.v1.UpdateTaskRequest
	7,  // 11: tasks.v1.TasksService.DeleteTask:input_type -> tasks.v1.DeleteTaskRequest
	10, // 12: tasks.v1.TasksService.Ping:input_type -> google.protobuf.Empty
	1,  // 13: tasks.v1.TasksService.CreateTask:output_type -> tasks.v1.Task
	1,  // 14: tasks.v1.TasksService.GetTask:output_type -> tasks.v1.Task
	5,  // 15: tasks.v1.TasksService.ListTask:output_type -> tasks.v1.ListTaskResponse
	1,  // 16: tasks.v1.TasksService.UpdateTask:output_type -> tasks.v1.Task
	10, // 17: tasks.v1.TasksService.DeleteTask:output_type -> google.protobuf.Empty
	10, // 18: tasks.v1.TasksService.Ping:output_type -> google.protobuf.Empty
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_tasks_tasks_proto_init() }
func file_proto_tasks_tasks_proto_init() {
	if File_proto_tasks_tasks_proto != nil {
		return
	}
	file_proto_tasks_tasks_proto_msgTypes[3].OneofWrappers = []any{
		(*ListTaskRequest_Status)(nil),
		(*ListTaskRequest_CategoryId)(nil),
		(*ListTaskRequest_WithoutCategory)(nil),
	}
	file_proto_tasks_tasks_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tasks_tasks_proto_rawDesc), len(file_proto_tasks_tasks_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tasks_tasks_proto_goTypes,
		DependencyIndexes: file_proto_tasks_tasks_proto_depIdxs,
		EnumInfos:         file_proto_tasks_tasks_proto_enumTypes,
		MessageInfos:      file_proto_tasks_tasks_proto_msgTypes,
	}.Build()
	File_proto_tasks_tasks_proto = out.File
	file_proto_tasks_tasks_proto_goTypes = nil
	file_proto_tasks_tasks_proto_depIdxs = nil
}
